"""RoboChallenge Table30v2 — data_config / embodiments / mixtures.

Auto-discovered by ``starVLA.dataloader.gr00t_lerobot.registry.discover_and_merge``.

Datasets live at::

    playground/Datasets/RoboChallenge_table30v2/lerobot/<task>/

each generated by ``examples/RoboChallenge_table30v2/train_files/convert_robochallenge_to_lerobot.py``.

All four robots use the same chunking convention:
    stride = 4, action_indices = range(0, 50 * stride, stride)
→ 50 action samples spanning 200 raw frames at 30 Hz (effective 7.5 Hz).
Per-robot state/action key lists differ by embodiment — see each subclass.
"""
from starVLA.dataloader.gr00t_lerobot.datasets import ModalityConfig
from starVLA.dataloader.gr00t_lerobot.transform.base import ComposedModalityTransform
from starVLA.dataloader.gr00t_lerobot.transform.state_action import (
    StateActionToTensor,
    StateActionTransform,
)
from starVLA.dataloader.gr00t_lerobot.embodiment_tags import EmbodimentTag


class _RoboChallengeUR5Config:
    """UR5 single-arm (2 cameras: cam_global, cam_arm).
    state(7) = joint_positions(6) + gripper_width(1)
    action(8) = ee_positions(7-quat) + gripper_width(1)
    """
    embodiment_tag = EmbodimentTag.TABLE30V2_UR5
    video_keys = ["video.cam_global", "video.cam_arm"]
    state_keys = ["state.joint_positions", "state.gripper_width"]
    action_keys = ["action.ee_positions", "action.gripper_width"]
    language_keys = ["annotation.human.task_description"]

    observation_indices = [0]
    state_indices = [0]
    stride = 4
    action_indices = list(range(0, 50 * stride, stride))

    def modality_config(self):
        return {
            "video":     ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state":     ModalityConfig(delta_indices=self.state_indices, modality_keys=self.state_keys),
            "action":    ModalityConfig(delta_indices=self.action_indices,      modality_keys=self.action_keys),
            "language":  ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={k: "q99" for k in self.state_keys},
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                normalization_modes={k: "q99" for k in self.action_keys},
            ),
        ])


class _RoboChallengeARX5Config(_RoboChallengeUR5Config):
    """ARX5 single-arm (3 cameras: cam_global, cam_arm, cam_side)."""
    embodiment_tag = EmbodimentTag.TABLE30V2_ARX5
    video_keys = ["video.cam_global", "video.cam_arm", "video.cam_side"]


class _RoboChallengeDOSW1Config(_RoboChallengeUR5Config):
    """DOS-W1 dual-arm (3 cameras: cam_high, cam_left_wrist, cam_right_wrist).
    state(14)  = L.joint(6) + L.grip(1) + R.joint(6) + R.grip(1)
    action(14) = same layout, abs joint targets.
    """
    embodiment_tag = EmbodimentTag.TABLE30V2_DOSW1
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]
    state_keys = [
        "state.left_joint_positions", "state.left_gripper_width",
        "state.right_joint_positions", "state.right_gripper_width",
    ]
    action_keys = [
        "action.left_joint_positions", "action.left_gripper_width",
        "action.right_joint_positions", "action.right_gripper_width",
    ]


class _RoboChallengeAlohaConfig(_RoboChallengeUR5Config):
    """ALOHA bimanual (3 cameras: cam_high, cam_left_wrist, cam_right_wrist).
    state(14)  = L.joint(6) + L.grip(1) + R.joint(6) + R.grip(1)
    action(16) = L.ee(7-quat) + L.grip(1) + R.ee(7-quat) + R.grip(1)
    """
    embodiment_tag = EmbodimentTag.TABLE30V2_ALOHA
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]
    state_keys = [
        "state.joint_positions_left",  "state.gripper_width_left",
        "state.joint_positions_right", "state.gripper_width_right",
    ]
    action_keys = [
        "action.ee_positions_left",  "action.gripper_width_left",
        "action.ee_positions_right", "action.gripper_width_right",
    ]


ROBOT_TYPE_CONFIG_MAP = {
    "ur5_robochallenge":   _RoboChallengeUR5Config(),
    "arx5_robochallenge":  _RoboChallengeARX5Config(),
    "dosw1_robochallenge": _RoboChallengeDOSW1Config(),
    "aloha_robochallenge": _RoboChallengeAlohaConfig(),
}

DATASET_NAMED_MIXTURES = {
    # --- minimal walk-through (1 task) ---
    "robochallenge_table30v2_shred_paper": [
        ("shred_paper", 1.0, "ur5_robochallenge"),
    ],
    "robochallenge_table30v2_lint_roller": [
        ("lint_roller_remove_dirt", 1.0, "aloha_robochallenge"),
    ],
    # --- UR5 single-arm ---
    "robochallenge_table30v2_ur5_all": [
        ("arrange_fruits",      1.0, "ur5_robochallenge"),
        ("item_classification", 1.0, "ur5_robochallenge"),
        ("shred_paper",         1.0, "ur5_robochallenge"),
    ],
    # --- ARX5 single-arm ---
    "robochallenge_table30v2_arx5_all": [
        ("arrange_flowers",              1.0, "arx5_robochallenge"),
        ("hang_the_cup",                 1.0, "arx5_robochallenge"),
        ("pick_out_the_green_blocks",    1.0, "arx5_robochallenge"),
        ("press_the_button",             1.0, "arx5_robochallenge"),
        ("turn_on_the_light_switch",     1.0, "arx5_robochallenge"),
        ("water_the_flowers",            1.0, "arx5_robochallenge"),
        ("wipe_the_table",               1.0, "arx5_robochallenge"),
    ],
    # --- DOS-W1 dual-arm ---
    "robochallenge_table30v2_dosw1_all": [
        ("fold_the_clothes",                1.0, "dosw1_robochallenge"),
        ("hold_the_tray_with_both_hands",   1.0, "dosw1_robochallenge"),
        ("place_objects_into_desk_drawer",  1.0, "dosw1_robochallenge"),
        ("put_in_pen_container",            1.0, "dosw1_robochallenge"),
        ("put_the_shoes_back",              1.0, "dosw1_robochallenge"),
        ("stack_bowls",                     1.0, "dosw1_robochallenge"),
        ("sweep_the_trash",                 1.0, "dosw1_robochallenge"),
        ("tidy_up_the_makeup_table",        1.0, "dosw1_robochallenge"),
        ("tie_a_knot",                      1.0, "dosw1_robochallenge"),
        ("untie_the_shoelaces",             1.0, "dosw1_robochallenge"),
    ],
    # --- ALOHA bimanual ---
    "robochallenge_table30v2_aloha_all": [
        ("lint_roller_remove_dirt",                 1.0, "aloha_robochallenge"),
        ("pack_the_items",                          1.0, "aloha_robochallenge"),
        ("pack_the_toothbrush_holder",              1.0, "aloha_robochallenge"),
        ("paint_jam",                               1.0, "aloha_robochallenge"),
        ("put_the_books_back",                      1.0, "aloha_robochallenge"),
        ("put_the_pencil_case_into_the_schoolbag",  1.0, "aloha_robochallenge"),
        ("scoop_with_a_small_spoon",                1.0, "aloha_robochallenge"),
        ("stamp_positioning",                       1.0, "aloha_robochallenge"),
        ("wipe_the_blackboard",                     1.0, "aloha_robochallenge"),
        ("wrap_with_a_soft_cloth",                  1.0, "aloha_robochallenge"),
    ],
}
